LANG=en_US.utf-8

export LANG

.PHONY: uv.lock
uv.lock:
	docker compose --progress=plain build --no-cache --build-arg RUN_UV_LOCK=true dev && \
	docker compose --progress=plain run --rm dev sh -c "cp -f /tmp/uv.lock /usr/src/patient_matching_service/uv.lock"

.PHONY:devdocker
devdocker: ## Builds the docker for dev
	docker compose build

.PHONY:init
init: uv.lock devdocker up setup-pre-commit  ## Initializes the local developer environment

.PHONY: up
up: ## Builds and starts the service in the background
	docker compose up --build -d --remove-orphans
	@echo ""
	@echo "patient_matching_service is up: http://localhost:5050"
	@if grep -qE '^ENABLE_TESTING_UI=(true|1|yes)$$' .env 2>/dev/null; then \
		echo "Testing UI:               http://localhost:5050/testing-ui"; \
	else \
		echo "Testing UI is disabled -- set ENABLE_TESTING_UI=true in .env and re-run 'make up' to expose it at http://localhost:5050/testing-ui"; \
	fi

.PHONY: down
down: ## Stops the service
	docker compose down

.PHONY:clean-pre-commit
clean-pre-commit: ## removes pre-commit hook
	rm -f "$$(git rev-parse --show-toplevel)/.git/hooks/pre-commit"

.PHONY:setup-pre-commit
setup-pre-commit:
	cp "$$(git rev-parse --show-toplevel)/pre-commit-hook" "$$(git rev-parse --show-toplevel)/.git/hooks/pre-commit" && \
	chmod +x "$$(git rev-parse --show-toplevel)/.git/hooks/pre-commit"

.PHONY:run-pre-commit
run-pre-commit: setup-pre-commit
	./pre-commit-hook pre_commit_all_files

.PHONY:update
update: down uv.lock setup-pre-commit devdocker  ## Updates all the packages using pyproject.toml

.PHONY:tests
tests: up
	docker compose run --rm --name patient_matching_service_tests dev pytest tests

.PHONY:shell
shell:devdocker ## Brings up the bash shell in dev docker
	docker compose run --rm --name patient_matching_service_shell dev sh

.PHONY: third-party-notices
third-party-notices: ## Regenerate THIRD-PARTY-NOTICES.md from the current dependency tree
	@echo "# Third-Party Notices" > THIRD-PARTY-NOTICES.md
	@echo "" >> THIRD-PARTY-NOTICES.md
	@echo "This file is generated by \`make third-party-notices\` — do not hand-edit." >> THIRD-PARTY-NOTICES.md
	@echo "" >> THIRD-PARTY-NOTICES.md
	@echo "## Python dependencies" >> THIRD-PARTY-NOTICES.md
	@echo "" >> THIRD-PARTY-NOTICES.md
	uv run pip-licenses --format=markdown --with-urls >> THIRD-PARTY-NOTICES.md

.DEFAULT_GOAL := help
.PHONY: help
help: ## Show this help.
	# from https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
