
bwell:
  environment: "dev-ue1"
  iamRole: arn:aws:iam::875300655693:role/dev-use1-irsa-patient-matching-service
  ingress:
    internal:
      enabled: true
      hosts:
        - host: patient-matching-service.dev.bwell.zone
          paths:
            - "/"
        - host: patient-matching-service.dev-ue1.bwell.zone
          paths:
            - "/"
    external:
      enabled: false

  env:

otel:
  enabled: true
  autoInstrumentation:
    enabled: true
    language: python
