
bwell:
  environment: "prod-ue1"
  iamRole: arn:aws:iam::400686897767:role/prod-irsa-patient-matching-service
  ingress:
    internal:
      enabled: true
      hosts:
        - host: patient-matching-service.prod.bwell.zone
          paths:
            - "/"
        - host: patient-matching-service.prod-ue1.bwell.zone
          paths:
            - "/"
    external:
      enabled: false

  env:
