
bwell:
  environment: "staging-ue1"
  iamRole: arn:aws:iam::435975920517:role/staging-irsa-patient-matching-service
  ingress:
    internal:
      enabled: true
      hosts:
        - host: patient-matching-service.staging.bwell.zone
          paths:
            - "/"
        - host: patient-matching-service.staging-ue1.bwell.zone
          paths:
            - "/"
    external:
      enabled: false

  env:

otel:
  enabled: true
  autoInstrumentation:
    enabled: true
    language: python
